## Bug in version 2.32.1 of docker compose
## https://github.com/compose-spec/compose-go/pull/721

name: sanglia_fly

services:
  kafka_broker:
    extends:
      service: kafka_broker
      file: kafka.compose.yml
    network_mode: ""
    networks:
      - backbone
  producer:
    extends:
      service: producer
      file: producer.compose.yml
    depends_on:
      kafka_broker:
        condition: service_healthy
        required: true
    environment:
      KAFKA_URL: kafka_broker:9092
    networks:
      - backbone
    scale: 3
  db:
    extends:
      service: db
      file: api.compose.yml
  bootstrap_db:
    extends:
      service: bootstrap_db
      file: api.compose.yml
  api:
    extends:
      service: api
      file: api.compose.yml
    depends_on:
      db:
        condition: service_healthy
        required: true
      bootstrap_db:
        condition: service_completed_successfully
        required: true
      kafka_broker:
        condition: service_healthy
        required: true
    environment:
      KAFKA_URL: kafka_broker:9092

networks:
  backbone:
    driver: bridge
