name: Deploy producer pipeline

on:
  push:
    branches:
      - master
    paths:
      - sanglia_fly_producer/**

jobs:
  deploy_producer:
    uses: ./.github/workflows/deploy.yml
    secrets:
      clever_token: ${{ secrets.clever_token }}
      clever_secret: ${{ secrets.clever_secret }}
      clever_app_id: ${{ secrets.producer_app_id }}
